### ISSUE TITLE
Will the project be updated？

### ISSUE THREAD

**Issue by PamiVOV** [Ncerzzk/mini_vtx#1]
您好！问问，项目还会更新吗？我看工程并没有完成。最近我有打算折腾一款VTX，用在自己穿越机上。两年前有参考过黑羊smartAudio协议。并用STM8完成过一款图传，但我并没有完整的原理图跟PCB。RTC6705的详细资料比较难找。

**Comment by Ncerzzk** [comment]
hi, 最近在折腾esp32做数字图传，这个模拟图传的项目近期不会更新了，除非esp32数字图传有重大缺陷，不然我应该是不会再转向模拟图传了。
